---
- name: Configure Infrastructure
  hosts: servers
  become: yes
  tasks:

    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - devs
        - testers
        - admins
        - auditors

    - name: Create users and assign them to groups
      user:
        name: "{{ item.name }}"
        groups: "{{ item.group }}"
        append: yes
        shell: /bin/bash
        create_home: yes
      loop:
        - { name: 'alice', group: 'devs' }
        - { name: 'bob', group: 'testers' }
        - { name: 'charlie', group: 'admins' }
        - { name: 'dave', group: 'auditors' }

